server:
  ubuntu_global:
    url: http://archive.ubuntu.com/ubuntu
  kakao_mirror:
    url: http://mirror.kakao.com/ubuntu
#    editions:
#      - name: focal
#        components:
#          - main
#          - restricted
#          - universe
#          - multiuniverse
#      - name: buster-updates
#        components:
#          - main
#          - contrib
#      - name: bionic
#        components:
#          - main
#          - restricted
#          - universe
#          - multiuniverse
