server:
  gitrepo:
    service: git
    url: https://github.com/zitryss/go-sample.git
  personaiam:
    service: github
    type: org
    url: https://github.com/personaiam
  steamit:
    service: github
    type: org
    url: