server:
  # https://docs.gradle.org/current/userguide/declaring_repositories.html
  centeral:
    id: maven-center
    name: Maven Center
    url: https://repo.maven.apache.org/maven2/
    description: "maven centeral"
  jcener:
    url: https://jcenter.bintray.com
    description: "jcenter"
#  google:
#    url: https://maven.google.com
#    description: "google android"
#  # https://repo.spring.io/webapp/#/home
#  spring_release:
#    name: repo.spring.io-releases
#    url: https://repo.spring.io/release
#  spring_snapshorts:
#    id: spring-snapshots
#    name: repo.spring.io-snapshots
#    url: https://repo.spring.io/snapshot

#  company_internal:
#    url: http://company
#    description: "my company"
#    auth:
#      method: BASIC
#      username:
